name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build API Docker Image
      run: |
        docker build -t myapi:latest ./api

    - name: Build Next.js Docker Image
      run: |
        docker build -t mynextapp:latest ./app

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.rouguii }}
        password: ${{ secrets.8RD98AN86@123 }}

    - name: Push API Docker Image
      run: |
        docker tag myapi:latest rouguii/myapi:latest
        docker push rouguii/myapi:latest

    - name: Push Next.js Docker Image
      run: |
        docker tag mynextapp:latest rouguii/mynextapp:latest
        docker push rouguii/mynextapp:latest
